services:
    facturizer.command.add_activity:
        class: Facturizer\Command\AddActivity
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: facturizer.command, alias: add-activity }

    facturizer.command.list_commands:
        class: Facturizer\Command\ListCommands
        arguments: ['@facturizer.registry.command_registry']
        tags:
            - { name: facturizer.command, alias: help }

    facturizer.command.list_projects:
        class: Facturizer\Command\ListProjects
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: facturizer.command, alias: projects }

    facturizer.command.add_project:
        class: Facturizer\Command\AddProject
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: facturizer.command, alias: add-project}

    facturizer.command.list_clients:
        class: Facturizer\Command\ListClients
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: facturizer.command, alias: clients}

    facturizer.command.add_client:
        class: Facturizer\Command\AddClient
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: facturizer.command, alias: add-client}
