services:
    facturizer.command.create_invoice:
        class: Facturizer\Command\CreateInvoice
        arguments:
            - '@facturizer.storage.clients'
            - '@facturizer.service.invoicing_service'
        tags:
            - { name: facturizer.command, alias: invoice}

    facturizer.command.book_activity:
        class: Facturizer\Command\BookActivity
        arguments: ['@facturizer.storage.clients']
        tags:
            - { name: facturizer.command, alias: ab}

    facturizer.command.list_activities:
        class: Facturizer\Command\ListActivities
        arguments: ['@facturizer.storage.clients']
        tags:
            - { name: facturizer.command, alias: al}

    facturizer.command.add_activity:
        class: Facturizer\Command\AddActivity
        arguments: ['@facturizer.storage.clients', '@facturizer.service.handle_service']
        tags:
            - { name: facturizer.command, alias: ac}

    facturizer.command.list_commands:
        class: Facturizer\Command\ListCommands
        arguments: ['@facturizer.registry.command_registry']
        tags:
            - { name: facturizer.command, alias: help }

    facturizer.command.list_projects:
        class: Facturizer\Command\ListProjects
        arguments: ['@facturizer.storage.clients']
        tags:
            - { name: facturizer.command, alias: pl }

    facturizer.command.add_project:
        class: Facturizer\Command\AddProject
        arguments: ['@facturizer.storage.clients', '@facturizer.service.handle_service']
        tags:
            - { name: facturizer.command, alias: pc}

    facturizer.command.list_clients:
        class: Facturizer\Command\ListClients
        arguments: ['@facturizer.storage.clients']
        tags:
            - { name: facturizer.command, alias: cl}

    facturizer.command.add_client:
        class: Facturizer\Command\AddClient
        arguments: ['@facturizer.storage.clients', '@facturizer.service.handle_service']
        tags:
            - { name: facturizer.command, alias: cc}
