services:
    facturizer.command.project_list:
        class: Facturizer\Command\ListProjects
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: facturizer.command, alias: project-list }
