imports:
- { resource: commands.yml }
- { resource: parameters.yml }

services:
    doctrine.config:
        class: Doctrine\ORM\Configuration
        factory_class: Doctrine\ORM\Tools\Setup
        factory_method: createAnnotationMetadataConfiguration
        arguments:
            - ['src/Entity']
            - true #devMode
            - ~
            - ~
            - false

    doctrine.orm.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory_class: Doctrine\ORM\EntityManager
        factory_method: create
        arguments:
            -
                driver: pdo_sqlite
                path: facturizer.db
            - '@doctrine.config'


    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [%template_path%]

    twig.environment:
        class: Twig_Environment
        arguments:
            - '@twig.loader'

    facturizer.registry.command_registry:
        class: Facturizer\Registry\CommandRegistry

    facturizer.service.invoicing_service:
        class: Facturizer\Service\InvoicingService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@twig.environment'
