imports:
- { resource: commands.yml }

services:
    facturizer.registry.command_registry:
        class: Facturizer\Registry\CommandRegistry

    facturizer.service.invoicing_service:
        class: Facturizer\Service\InvoicingService
        arguments:
            - '@facturizer.storage.clients'
            - '@twig.environment'

    facturizer.storage.clients:
        class: Facturizer\Storage\ObjectStorage
        arguments:
            - '@filesystem'
            - '@serializer'
            - %storage_path%
            - 'Facturizer\Entity\Client'
            - 'clients'

    facturizer.service.handle_service:
        class: Facturizer\Service\HandleService
        arguments:
            - '@facturizer.storage.clients'

    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [%template_path%]

    twig.environment:
        class: Twig_Environment
        arguments:
           - '@twig.loader'

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    serializer_builder:
        class: JMS\Serializer\SerializerBuilder
    serializer:
        class: JMS\Serializer\Serializer
        factory_service: serializer_builder
        factory_method: build
